### ISSUE TITLE
SSL certification with Report Portal  (Tests are not going through because the site has SSL certification)

### ISSUE THREAD

**Issue by Shivin89** [reportportal/agent-java-cucumber6#11]
Hi Team,

After migrating the report portal to our company server and adding SSL certification on it (rp. endpoint changed to https), Now the tests are not going through and we are seeing the below error.

I am using  java cucumber6 5.0.1 

I tested with Nunit framework one and it works fine with SSL certification.

ERROR c.e.r.s.ReportPortal - main - Cannot build ReportPortal client
com.epam.reportportal.exception.InternalReportPortalClientException: Unable to load trust store
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:533)
	at com.epam.reportportal.service.ReportPortal$Builder.lambda$buildClient$1(ReportPortal.java:449)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:449)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:416)
	at com.epam.reportportal.cucumber.AbstractReporter.<clinit>(AbstractReporter.java:132)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at io.cucumber.core.plugin.PluginFactory.newInstance(PluginFactory.java:116)
	at io.cucumber.core.plugin.PluginFactory.instantiate(PluginFactory.java:79)
	at io.cucumber.core.plugin.PluginFactory.create(PluginFactory.java:63)
	at io.cucumber.core.plugin.Plugins.createPlugins(Plugins.java:32)
	at io.cucumber.core.plugin.Plugins.<init>(Plugins.java:25)
	at io.cucumber.junit.Cucumber.<init>(Cucumber.java:162)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:76)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:49)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:526)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
16:53:22.538 ERROR c.e.r.s.ReportPortal - main - Cannot build ReportPortal client
com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:456)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:416)
	at com.epam.reportportal.cucumber.AbstractReporter.<clinit>(AbstractReporter.java:132)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at io.cucumber.core.plugin.PluginFactory.newInstance(PluginFactory.java:116)
	at io.cucumber.core.plugin.PluginFactory.instantiate(PluginFactory.java:79)
	at io.cucumber.core.plugin.PluginFactory.create(PluginFactory.java:63)
	at io.cucumber.core.plugin.Plugins.createPlugins(Plugins.java:32)
	at io.cucumber.core.plugin.Plugins.<init>(Plugins.java:25)
	at io.cucumber.junit.Cucumber.<init>(Cucumber.java:162)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:76)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:49)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:526)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: com.epam.reportportal.exception.InternalReportPortalClientException: Unable to load trust store
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:533)
	at com.epam.reportportal.service.ReportPortal$Builder.lambda$buildClient$1(ReportPortal.java:449)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:449)

**Comment by HardNorth** [comment]
Have you posted complete stack trace? There is not enough information to tell what's happened.

**Comment by Shivin89** [comment]
@HardNorth 
MyTestRunner (12)
testrunners.MyTestRunner
initializationError(testrunners.MyTestRunner)
java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at io.cucumber.core.plugin.PluginFactory.newInstance(PluginFactory.java:116)
	at io.cucumber.core.plugin.PluginFactory.instantiate(PluginFactory.java:79)
	at io.cucumber.core.plugin.PluginFactory.create(PluginFactory.java:63)
	at io.cucumber.core.plugin.Plugins.createPlugins(Plugins.java:32)
	at io.cucumber.core.plugin.Plugins.<init>(Plugins.java:25)
	at io.cucumber.junit.Cucumber.<init>(Cucumber.java:162)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:76)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:49)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:526)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:424)
	at com.epam.reportportal.cucumber.AbstractReporter.<clinit>(AbstractReporter.java:132)
	... 30 more
Caused by: com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:456)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:416)
	... 31 more
Caused by: com.epam.reportportal.exception.InternalReportPortalClientException: Unable to load trust store
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:533)
	at com.epam.reportportal.service.ReportPortal$Builder.lambda$buildClient$1(ReportPortal.java:449)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:449)
	... 32 more

**Comment by HardNorth** [comment]
@Shivin89 U cannot say anything specific, only guess that you specified wrong keystore path or password.

**Comment by Shivin89** [comment]
Actually, I am not providing anything in the Keystore path or password.(Default).. The issue is if I generate JKS file and provide the path there then I need to change in Bamboo and everyone using the automation framework needs to provide the same.
I am looking for a smart resolution like I saw in C# you can have Callback set to false (Something like that)

**Comment by HardNorth** [comment]
Java is not C#. You have to specify keystore if you are using custom certificates.

**Comment by Shivin89** [comment]
ohk , Thanks
