### ISSUE TITLE
Report Portal returned error CHILD_START_TIME_EARLIER_THAN_PARENT

### ISSUE THREAD

**Issue by LienaBondarenko** [reportportal/agent-java-cucumber6#7]
Client version 5.0.11
Agent version 5.0.0-RC-1

Some scenarios are not present in RP launch but were run in GitLab job.
Logs contain error:

28-10-2020 07:35:57.204 [rp-io-8] ERROR c.e.r.utils.SubscriptionUtils.onError - Start test item completed with error 
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Start time of child ['Wed Oct 28 07:35:57 UTC 2020'] item should be same or later than start time ['2020-10-28T07:35:57.085'] of the parent item/launch '15122524'
Error Type: CHILD_START_TIME_EARLIER_THAN_PARENT
	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:85)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:61)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:526)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Reproduces randomly on different launches.

![image](https://user-images.githubusercontent.com/11560912/99841640-2cf09900-2b77-11eb-9006-133e6abc7b6a.png)
![image](https://user-images.githubusercontent.com/11560912/99841850-7e992380-2b77-11eb-842b-f0adc82b3794.png)

**Comment by HardNorth** [comment]
Fixed: https://github.com/reportportal/agent-java-cucumber6/releases/tag/5.0.1
